-- PROGRESSION - 1

-- 1. **Create table city**
CREATE TABLE CITY 
(
 ID NUMBER(11) PRIMARY KEY,
 NAME VARCHAR(50) NOT NULL   
);
-- 2. **Create table referee**
CREATE TABLE REFEREE(
    ID NUMBER(11) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);
-- 3. **Create table innings**
CREATE TABLE INNINGS(
    ID NUMBER(11) PRIMARY KEY,
    INNINGS_NUMBER NUMBER(11) NOT NULL
);
-- 4. **Create table extra_type**
CREATE TABLE EXTRA_TYPE(
    ID NUMBER(11) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);
-- 5. **Create table skill**
CREATE TABLE SKILL(
    ID NUMBER(11) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);
-- 6. **Create table team**
CREATE TABLE TEAM(
    ID NUMBER(11) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    COACH VARCHAR(50)  NOT NULL,
    HOME_CITY NUMBER(11)  NOT NULL,
    FOREIGN KEY(HOME_CITY) REFERENCES CITY(ID),
    CAPTAIN NUMBER(11) NOT NULL
);
-- 7. **Create table player**
CREATE TABLE PLAYER(
    ID NUMBER(11) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    SKILL_ID NUMBER(11) NOT NULL,
    FOREIGN KEY(SKILL_ID) REFERENCES SKILL(ID),
    TEAM_ID NUMBER(11) NOT NULL,
    FOREIGN KEY(TEAM_ID) REFERENCES TEAM(ID)
);
-- 8. **Create table venue**
 CREATE TABLE VENUE(
        ID NUMBER(11) PRIMARY KEY,
        STADIUM_NAME VARCHAR(50) NOT NULL,
        CITY_ID NUMBER(11) NOT NULL,
        FOREIGN KEY(CITY_ID) REFERENCES CITY(ID)
);
-- 9. **Create table event**
CREATE TABLE EVENT(
    ID NUMBER(11) PRIMARY KEY,
    INNINGS_ID NUMBER(11) NOT NULL,
    FOREIGN KEY(INNINGS_ID) REFERENCES INNINGS(ID),
    EVENT_NO NUMBER(11) NOT NULL,
    RAIDER_ID NUMBER(11) NOT NULL,
    FOREIGN KEY(RAIDER_ID) REFERENCES PLAYER(ID),
    RAID_POINTS NUMBER(11) NOT NULL,
    DEFENDING_POINTS NUMBER(11) NOT NULL,
    CLOCK_IN_SECONDS NUMBER(11) NOT NULL,
    TEAM_ONE_SCORE NUMBER(11) NOT NULL,
    TEAM_TWO_SCORE NUMBER(11) NOT NULL
);
-- 10. **Create table extra_event**
CREATE TABLE EXTRA_EVENT(
    ID NUMBER(11) PRIMARY KEY,
    EVENT_ID NUMBER(11) NOT NULL,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID),
    EXTRA_TYPE_ID NUMBER(11) NOT NULL,
    FOREIGN KEY(EXTRA_TYPE_ID) REFERENCES EXTRA_TYPE(ID),
    POINTS NUMBER(11) NOT NULL,
    SCORING_TEAM_ID NUMBER(11) NOT NULL,
    FOREIGN KEY(SCORING_TEAM_ID) REFERENCES EVENT(TEAM_ONE_SCORE,TEAM_TWO_SCORE)
);
-- 11. **Create table outcome**
CREATE TABLE OUTCOME(
    ID NUMBER(11) PRIMARY KEY,
    STATUS VARCHAR(100) NOT NULL,
    WINNER_TEAM_ID NUMBER(11) NULL,
    FOREIGN KEY(WINNER_TEAM_ID) REFERENCES GAME(TEAM_ID_1,TEAM_ID_2),
    SCORE NUMBER(11) NULL,
    PLAYER_OF_MATCH NUMBER(11) NULL,
    FOREIGN KEY(PLAYER_OF_MATCH) REFERENCES PLAYER(ID)
);
-- 12. **Create table game**
CREATE TABLE GAME(
    ID  NUMBER(11) PRIMARY KEY,
    GAME_DATE DATE NOT NULL,
    TEAM_ID_1 NUMBER(11) NOT NULL,
    FOREIGN KEY(TEAM_ID_1) REFERENCES TEAM(ID),
    TEAM_ID_2 NUMBER(11) NOT NULL,
    FOREIGN KEY(TEAM_ID_2) REFERENCES TEAM(ID),
    VENUE_ID NUMBER(11) NOT NULL,
    FOREIGN KEY (VENUE_ID) REFERENCES VENUE(ID),
    OUTCOME_ID NUMBER(11) NOT NULL,
    FOREIGN KEY(OUTCOME_ID) REFERENCES OUTCOME(ID),
    REFEREE_ID_1 NUMBER(11) NOT NULL,
    FOREIGN KEY (REFEREE_ID_1) REFERENCES REFEREE(ID),
    REFEREE_ID_2 NUMBER(11) NOT NULL,
    FOREIGN KEY (REFEREE_ID_2) REFERENCES REFEREE(ID),
    FIRST_INNINGS_ID NUMBER(11) NOT NULL,
    FOREIGN KEY(FIRST_INNINGS_ID) REFERENCES INNINGS(ID),
    SECOND_INNINGS_ID NUMBER(11) NOT NULL,
    FOREIGN KEY(SECOND_INNINGS_ID) REFERENCES INNINGS(ID)
);
-- 13. **Drop table city**
DROP TABLE CITY;
-- 14. **Drop table innings**
DROP TABLE INNINGS;
-- 15. **Drop table skill**
DROP TABLE SKILL;
-- 16. **Drop table extra_type**
DROP TABLE EXTRA_TYPE;